name: CD Pipeline - Prod

on:
  push:
    branches:
      - prod

jobs:
  security_scan:
    name: Job 1 - Security Scan Before Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install trivy -y

      - name: Scan image from Docker Hub
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev

  deploy:
    name: Job 2 - Deploy on Production
    runs-on: [self-hosted, runner_prod]
    needs: security_scan
    steps:
      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev

      - name: Stop existing container
        run: docker stop intranet-prod || true && docker rm intranet-prod || true

      - name: Run container on port 80
        run: |
          docker run -d \
            --name intranet-prod \
            -p 80:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev